apiVersion: v2
name: clops-helm
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: "45.18.*"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: kube-prometheus-stack.enabled

  - name: metrics-server
    version: "3.8.*"
    repository: "https://kubernetes-sigs.github.io/metrics-server/"
    condition: metrics-server.enabled

  - name: grafana
    version: "6.54.*"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled

  - name: loki
    version: "5.0.*"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled

  - name: promtail
    version: "6.11.*"
    repository: "https://grafana.github.io/helm-charts"
    condition: promtail.enabled

  - name: prometheus-blackbox-exporter
    version: "7.7.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-blackbox-exporter.enabled
